// Generated by poodle-icons. Do not edit.
type IconNodes = [string, Record<string, string>][];

export const icons: Record<string, IconNodes> = {
  "briefcase-business": [
    [
      "path",
      {
        "d": "M12 12h.01"
      }
    ],
    [
      "path",
      {
        "d": "M16 6V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2"
      }
    ],
    [
      "path",
      {
        "d": "M22 13a18.15 18.15 0 0 1-20 0"
      }
    ],
    [
      "rect",
      {
        "width": "20",
        "height": "14",
        "x": "2",
        "y": "6",
        "rx": "2"
      }
    ]
  ],
  "folder-open": [
    [
      "path",
      {
        "d": "m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2"
      }
    ]
  ],
  "list-todo": [
    [
      "path",
      {
        "d": "M13 5h8"
      }
    ],
    [
      "path",
      {
        "d": "M13 12h8"
      }
    ],
    [
      "path",
      {
        "d": "M13 19h8"
      }
    ],
    [
      "path",
      {
        "d": "m3 17 2 2 4-4"
      }
    ],
    [
      "rect",
      {
        "x": "3",
        "y": "4",
        "width": "6",
        "height": "6",
        "rx": "1"
      }
    ]
  ],
  "square-check": [
    [
      "rect",
      {
        "width": "18",
        "height": "18",
        "x": "3",
        "y": "3",
        "rx": "2"
      }
    ],
    [
      "path",
      {
        "d": "m9 12 2 2 4-4"
      }
    ]
  ]
};

export const briefcaseBusiness = icons["briefcase-business"];
export const folderOpen = icons["folder-open"];
export const listTodo = icons["list-todo"];
export const squareCheck = icons["square-check"];
