[catalog]
alias = "acme-client"

[package_manager]
js = "bun"

[tasks]
health = [{ task = "check" }]
validate = [
  { task = "check" },
  { task = "build" }
]
qa = [{ task = "validate" }]

[tasks.build]
run = "bun x tsc -p tsconfig.json"

[tasks.check]
run = "bun x tsc -p tsconfig.json --noEmit"
