[package]
name = "acme-db"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
dotenvy = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
underlay-audit = { workspace = true }
underlay-db = { workspace = true }
underlay-devtools = { workspace = true }
underlay-email = { workspace = true }
underlay-http = { workspace = true }
underlay-query = { workspace = true }
underlay-media = { workspace = true, features = ["nightfire"] }
underlay-nightfire = { workspace = true }
uuid = { workspace = true }

[[bin]]
name = "migrate_dev_db"
path = "src/bin/migrate_dev_db.rs"

[[bin]]
name = "reset_dev_db"
path = "src/bin/reset_dev_db.rs"
